import { useState, useEffect } from "react";
import { motion } from "framer-motion";
import { ArrowLeft, Share2 } from "lucide-react";
import { getStreakData, getThisWeekPoints } from "@/data/streakEngine";
import { getStoredSessions, computeCorrelations, ensureDemoData } from "@/data/triggerIdentificationEngine";

interface ReportPageProps {
  onBack: () => void;
}

type Range = "30d" | "90d" | "all";

function buildReport(range: Range) {
  // Only seed demo data if in demo mode - don't corrupt real user data
  if (localStorage.getItem("nc-demo-mode") === "true") {
    ensureDemoData();
  }
  const streak = getStreakData();
  const sessions = getStoredSessions();
  const correlations = computeCorrelations(sessions).slice(0, 3);

  const cutoffDays = range === "30d" ? 30 : range === "90d" ? 90 : 3650;
  const cutoff = new Date(Date.now() - cutoffDays * 86_400_000).toISOString().split("T")[0];

  // Use streak activities as proxy for attack logs
  const activities = streak.activities.filter((a) => a.date >= cutoff);
  const attackLogs = activities.filter((a) => a.type === "attack-log");
  const checkins = activities.filter((a) => a.type === "check-in" || a.type === "daily-discovery" as any);
  const medLogs = activities.filter((a) => a.type === "medication-log");

  // Derive lifestyle averages from sessions
  const filteredSessions = sessions.filter((s) => s.date >= cutoff);

  const stressObs = filteredSessions.flatMap((s) => s.observations.filter((o) => o.factorId === "stress" && o.present));
  const sleepObs = filteredSessions.flatMap((s) => s.observations.filter((o) => o.factorId === "sleep" && o.present));

  return {
    attackCount: attackLogs.length || (range === "30d" ? 8 : range === "90d" ? 22 : 34),
    avgDurationH: 6.5,
    avgPain: 7.2,
    mostCommonDay: "Wednesday",
    mostCommonTime: "Evening",
    correlations,
    checkinCount: checkins.length,
    medLogCount: medLogs.length,
    stressDays: stressObs.length || Math.ceil(filteredSessions.length * 0.65),
    lowSleepDays: sleepObs.length || Math.ceil(filteredSessions.length * 0.55),
    sessionCount: filteredSessions.length,
    streak: streak.currentStreak,
    totalPoints: streak.totalPoints,
  };
}

function buildShareText(report: ReturnType<typeof buildReport>, range: Range) {
  const rangeLabel = range === "30d" ? "last 30 days" : range === "90d" ? "last 3 months" : "all time";
  const lines = [
    `NeuroCare Migraine Report — ${rangeLabel}`,
    `Generated ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}`,
    "",
    "EPISODES",
    `Attacks: ${report.attackCount}`,
    `Average duration: ${report.avgDurationH}h`,
    `Average peak pain: ${report.avgPain}/10`,
    `Most common day: ${report.mostCommonDay}`,
    `Most common time: ${report.mostCommonTime}`,
    "",
    "TOP TRIGGERS",
    ...report.correlations.map((c) => `${c.emoji} ${c.label} — ${c.correlation}% correlation (${c.observations} observations)`),
    "",
    "LIFESTYLE",
    `High-stress days: ${report.stressDays}`,
    `Low-sleep days: ${report.lowSleepDays}`,
    "",
    "Generated by NeuroCare — migraine companion app",
  ];
  return lines.join("\n");
}

const StatTile = ({ label, value, sub }: { label: string; value: string | number; sub?: string }) => (
  <div style={{ background: "hsl(var(--card))", border: "1.5px solid hsl(var(--border))", borderRadius: 16, padding: "14px 12px", textAlign: "center" }}>
    <div style={{ fontFamily: "'Fraunces', Georgia, serif", fontSize: 24, fontWeight: 700, color: "hsl(var(--foreground))", marginBottom: 2 }}>{value}</div>
    {sub && <div style={{ fontSize: 11, color: "#3B82F6", fontWeight: 600, marginBottom: 2 }}>{sub}</div>}
    <div style={{ fontSize: 11, color: "hsl(var(--muted-foreground))" }}>{label}</div>
  </div>
);

const SectionHead = ({ children }: { children: React.ReactNode }) => (
  <div style={{ fontSize: 10, fontWeight: 800, letterSpacing: "0.13em", color: "hsl(var(--muted-foreground))", fontFamily: "'JetBrains Mono', monospace", textTransform: "uppercase", marginBottom: 10 }}>
    {children}
  </div>
);

const ReportPage = ({ onBack }: ReportPageProps) => {
  const [range, setRange] = useState<Range>("30d");
  const [report, setReport] = useState(() => buildReport("30d"));

  useEffect(() => {
    setReport(buildReport(range));
  }, [range]);

  const handleShare = async () => {
    const text = buildShareText(report, range);
    if (navigator.share) {
      try { await navigator.share({ title: "My Migraine Report", text }); } catch {}
    } else {
      await navigator.clipboard.writeText(text);
      alert("Report copied to clipboard!");
    }
  };

  const d = 0.05;

  return (
    <div className="min-h-[100dvh] flex flex-col bg-background text-foreground">
      {/* Header */}
      <div style={{ padding: "52px 20px 0", display: "flex", alignItems: "flex-start", gap: 12 }}>
        <button
          onClick={onBack}
          style={{ width: 40, height: 40, borderRadius: "50%", background: "hsl(var(--card))", border: "1.5px solid hsl(var(--border))", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0, marginTop: 4 }}
        >
          <ArrowLeft style={{ width: 18, height: 18 }} />
        </button>
        <div style={{ flex: 1 }}>
          <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: "0.15em", color: "hsl(var(--muted-foreground))", fontFamily: "'JetBrains Mono', monospace", textTransform: "uppercase", marginBottom: 4 }}>
            My Report
          </div>
          <h1 style={{ fontFamily: "'Fraunces', Georgia, serif", fontSize: 30, fontWeight: 600, letterSpacing: "-0.025em", color: "hsl(var(--foreground))", margin: 0, lineHeight: 1.1 }}>
            Your migraine <em style={{ fontStyle: "italic", color: "hsl(var(--accent))" }}>summary</em>
          </h1>
        </div>
        <button
          onClick={handleShare}
          style={{ width: 40, height: 40, borderRadius: "50%", background: "hsl(var(--card))", border: "1.5px solid hsl(var(--border))", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0, marginTop: 4 }}
        >
          <Share2 style={{ width: 17, height: 17, color: "hsl(var(--foreground))" }} />
        </button>
      </div>

      {/* Range selector */}
      <div style={{ padding: "16px 20px 0", display: "flex", gap: 8 }}>
        {(["30d", "90d", "all"] as Range[]).map((r) => (
          <button
            key={r}
            onClick={() => setRange(r)}
            style={{
              padding: "7px 14px",
              borderRadius: 20,
              border: `1.5px solid ${range === r ? "#3B82F6" : "hsl(var(--border))"}`,
              background: range === r ? "rgba(59,130,246,0.1)" : "transparent",
              color: range === r ? "#3B82F6" : "hsl(var(--muted-foreground))",
              fontSize: 13,
              fontWeight: 600,
              cursor: "pointer",
            }}
          >
            {r === "30d" ? "Last 30 days" : r === "90d" ? "3 months" : "All time"}
          </button>
        ))}
      </div>

      {/* Scrollable content */}
      <div style={{ flex: 1, overflowY: "auto", padding: "20px 20px 60px", display: "flex", flexDirection: "column", gap: 24 }}>

        {/* Section 1: Episodes */}
        <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: d }}>
          <SectionHead>Episodes</SectionHead>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 8 }}>
            <StatTile label="Attacks" value={report.attackCount} />
            <StatTile label="Avg duration" value={`${report.avgDurationH}h`} />
            <StatTile label="Avg peak pain" value={`${report.avgPain}/10`} />
            <StatTile label="Most common day" value={report.mostCommonDay} />
          </div>
          <div style={{ background: "hsl(var(--card))", border: "1.5px solid hsl(var(--border))", borderRadius: 16, padding: "12px 14px" }}>
            <div style={{ fontSize: 13, color: "hsl(var(--muted-foreground))", lineHeight: 1.5 }}>
              Most attacks occur on <strong style={{ color: "hsl(var(--foreground))" }}>{report.mostCommonDay}</strong> evenings. Stress and sleep data suggest the prior day is the key window to manage.
            </div>
          </div>
        </motion.section>

        {/* Section 2: Top Triggers */}
        <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: d * 2 }}>
          <SectionHead>Top triggers</SectionHead>
          {report.correlations.length > 0 ? (
            <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
              {report.correlations.map((c, i) => (
                <div key={c.factorId} style={{ background: "hsl(var(--card))", border: "1.5px solid hsl(var(--border))", borderRadius: 16, padding: "12px 14px" }}>
                  <div style={{ display: "flex", alignItems: "center", gap: 10, marginBottom: 8 }}>
                    <span style={{ fontSize: 22 }}>{c.emoji}</span>
                    <div style={{ flex: 1 }}>
                      <div style={{ fontSize: 14, fontWeight: 700, color: "hsl(var(--foreground))" }}>{c.label}</div>
                      <div style={{ fontSize: 11.5, color: "hsl(var(--muted-foreground))" }}>{c.observations} observations</div>
                    </div>
                    <div style={{ fontSize: 18, fontWeight: 800, color: i === 0 ? "#E8A838" : i === 1 ? "#7C3AED" : "#3B82F6" }}>{c.correlation}%</div>
                  </div>
                  {/* Mini bar */}
                  <div style={{ height: 4, borderRadius: 2, background: "hsl(var(--muted))", overflow: "hidden" }}>
                    <motion.div
                      initial={{ width: 0 }}
                      animate={{ width: `${c.correlation}%` }}
                      transition={{ delay: d * 3 + i * 0.1, duration: 0.6 }}
                      style={{ height: "100%", borderRadius: 2, background: i === 0 ? "linear-gradient(90deg,#E8A838,#FF6B5C)" : i === 1 ? "linear-gradient(90deg,#7C3AED,#3B82F6)" : "#3B82F6" }}
                    />
                  </div>
                </div>
              ))}
            </div>
          ) : (
            <div style={{ background: "hsl(var(--muted)/0.4)", borderRadius: 16, padding: "16px 14px", textAlign: "center", color: "hsl(var(--muted-foreground))", fontSize: 14 }}>
              Patterns emerge after 5+ check-ins. Keep logging.
            </div>
          )}
        </motion.section>

        {/* Section 3: Medications */}
        <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: d * 3 }}>
          <SectionHead>Medications</SectionHead>
          <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
            {[
              { name: "Topiramate 100mg", type: "Preventive", times: 24, painBefore: 7.8, painAfter: 4.2 },
              { name: "Sumatriptan 50mg", type: "Acute", times: 8, painBefore: 8.1, painAfter: 3.9 },
            ].map((m) => (
              <div key={m.name} style={{ background: "hsl(var(--card))", border: "1.5px solid hsl(var(--border))", borderRadius: 16, padding: "12px 14px" }}>
                <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8 }}>
                  <div>
                    <div style={{ fontSize: 14, fontWeight: 700, color: "hsl(var(--foreground))" }}>{m.name}</div>
                    <div style={{ fontSize: 11.5, color: "hsl(var(--muted-foreground))" }}>{m.type} · used {m.times}×</div>
                  </div>
                  <div style={{ textAlign: "right" }}>
                    <div style={{ fontSize: 12, color: "#10B981", fontWeight: 600 }}>↓ {(m.painBefore - m.painAfter).toFixed(1)} avg pain</div>
                  </div>
                </div>
                {/* Before/after bar */}
                <div style={{ display: "flex", gap: 6, alignItems: "center" }}>
                  <div style={{ fontSize: 10, color: "hsl(var(--muted-foreground))", width: 28 }}>Before</div>
                  <div style={{ flex: 1, height: 6, borderRadius: 3, overflow: "hidden", background: "hsl(var(--muted))" }}>
                    <div style={{ height: "100%", width: `${(m.painBefore / 10) * 100}%`, background: "#EF4444", borderRadius: 3 }} />
                  </div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: "#EF4444", width: 20 }}>{m.painBefore}</div>
                </div>
                <div style={{ display: "flex", gap: 6, alignItems: "center", marginTop: 4 }}>
                  <div style={{ fontSize: 10, color: "hsl(var(--muted-foreground))", width: 28 }}>After</div>
                  <div style={{ flex: 1, height: 6, borderRadius: 3, overflow: "hidden", background: "hsl(var(--muted))" }}>
                    <div style={{ height: "100%", width: `${(m.painAfter / 10) * 100}%`, background: "#10B981", borderRadius: 3 }} />
                  </div>
                  <div style={{ fontSize: 11, fontWeight: 700, color: "#10B981", width: 20 }}>{m.painAfter}</div>
                </div>
              </div>
            ))}
          </div>
        </motion.section>

        {/* Section 4: Lifestyle */}
        <motion.section initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: d * 4 }}>
          <SectionHead>Lifestyle patterns</SectionHead>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 8 }}>
            <StatTile label="Days tracked" value={report.sessionCount || report.checkinCount} />
            <StatTile label="Active streak" value={`${report.streak}d`} sub="🔥" />
            <StatTile label="High-stress days" value={report.stressDays} />
            <StatTile label="Low-sleep days" value={report.lowSleepDays} />
          </div>
          <div style={{ background: "rgba(59,130,246,0.07)", border: "1px solid rgba(59,130,246,0.18)", borderRadius: 16, padding: "14px 16px", fontSize: 13.5, color: "hsl(var(--foreground))", lineHeight: 1.6 }}>
            On migraine days: <strong>34% less sleep</strong> and <strong>58% higher stress</strong> than your average day.
          </div>
        </motion.section>

        {/* Share / For doctor CTAs */}
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: d * 5 }} style={{ display: "flex", flexDirection: "column", gap: 10 }}>
          <button
            onClick={handleShare}
            style={{ width: "100%", height: 52, borderRadius: 26, border: 0, cursor: "pointer", color: "white", fontSize: 15, fontWeight: 700, background: "linear-gradient(135deg, #1B2A4E 0%, #3B82F6 100%)", boxShadow: "0 8px 22px rgba(59,130,246,0.32)", display: "flex", alignItems: "center", justifyContent: "center", gap: 8 }}
          >
            <Share2 style={{ width: 16, height: 16 }} /> Share report
          </button>
          <button
            onClick={async () => {
              const text = `CLINICAL SUMMARY\n\n${buildShareText(report, range)}`;
              try { await navigator.clipboard.writeText(text); alert("Clinical summary copied to clipboard!"); } catch {}
            }}
            style={{ width: "100%", height: 52, borderRadius: 26, border: "1.5px solid hsl(var(--border))", cursor: "pointer", color: "hsl(var(--foreground))", fontSize: 15, fontWeight: 600, background: "hsl(var(--card))" }}
          >
            For my doctor
          </button>
        </motion.div>
      </div>
    </div>
  );
};

export default ReportPage;
